version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/jyp
    overwrite: true
    file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 300
      runas: ec2-user
