version: '3.7'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jyp_container
    volumes:
      - /home/ec2-user/jyp/:/home/jyp
    ports:
      - "80:80"
    privileged: true
